#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
OUT_DEBUG = bin\\Debug\\MBtest.exe

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\MBtest.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\\unitTests.o $(OBJDIR_DEBUG)\\modbus_library\\mb.o $(OBJDIR_DEBUG)\\modbus_library\\crc.o $(OBJDIR_DEBUG)\\main.o $(OBJDIR_DEBUG)\\functions\\f06.o $(OBJDIR_DEBUG)\\functions\\f03.o $(OBJDIR_DEBUG)\\drivers\\uartDriver.o $(OBJDIR_DEBUG)\\drivers\\timerDriver.o $(OBJDIR_DEBUG)\\drivers\\mcDriver.o $(OBJDIR_DEBUG)\\bsp.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\unitTests.o $(OBJDIR_RELEASE)\\modbus_library\\mb.o $(OBJDIR_RELEASE)\\modbus_library\\crc.o $(OBJDIR_RELEASE)\\main.o $(OBJDIR_RELEASE)\\functions\\f06.o $(OBJDIR_RELEASE)\\functions\\f03.o $(OBJDIR_RELEASE)\\drivers\\uartDriver.o $(OBJDIR_RELEASE)\\drivers\\timerDriver.o $(OBJDIR_RELEASE)\\drivers\\mcDriver.o $(OBJDIR_RELEASE)\\bsp.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG) md $(OBJDIR_DEBUG)
	cmd /c if not exist $(OBJDIR_DEBUG)\\modbus_library md $(OBJDIR_DEBUG)\\modbus_library
	cmd /c if not exist $(OBJDIR_DEBUG)\\functions md $(OBJDIR_DEBUG)\\functions
	cmd /c if not exist $(OBJDIR_DEBUG)\\drivers md $(OBJDIR_DEBUG)\\drivers

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\unitTests.o: unitTests.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c unitTests.c -o $(OBJDIR_DEBUG)\\unitTests.o

$(OBJDIR_DEBUG)\\modbus_library\\mb.o: modbus_library\\mb.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c modbus_library\\mb.c -o $(OBJDIR_DEBUG)\\modbus_library\\mb.o

$(OBJDIR_DEBUG)\\modbus_library\\crc.o: modbus_library\\crc.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c modbus_library\\crc.c -o $(OBJDIR_DEBUG)\\modbus_library\\crc.o

$(OBJDIR_DEBUG)\\main.o: main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.c -o $(OBJDIR_DEBUG)\\main.o

$(OBJDIR_DEBUG)\\functions\\f06.o: functions\\f06.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c functions\\f06.c -o $(OBJDIR_DEBUG)\\functions\\f06.o

$(OBJDIR_DEBUG)\\functions\\f03.o: functions\\f03.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c functions\\f03.c -o $(OBJDIR_DEBUG)\\functions\\f03.o

$(OBJDIR_DEBUG)\\drivers\\uartDriver.o: drivers\\uartDriver.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c drivers\\uartDriver.c -o $(OBJDIR_DEBUG)\\drivers\\uartDriver.o

$(OBJDIR_DEBUG)\\drivers\\timerDriver.o: drivers\\timerDriver.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c drivers\\timerDriver.c -o $(OBJDIR_DEBUG)\\drivers\\timerDriver.o

$(OBJDIR_DEBUG)\\drivers\\mcDriver.o: drivers\\mcDriver.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c drivers\\mcDriver.c -o $(OBJDIR_DEBUG)\\drivers\\mcDriver.o

$(OBJDIR_DEBUG)\\bsp.o: bsp.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c bsp.c -o $(OBJDIR_DEBUG)\\bsp.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)
	cmd /c rd $(OBJDIR_DEBUG)\\modbus_library
	cmd /c rd $(OBJDIR_DEBUG)\\functions
	cmd /c rd $(OBJDIR_DEBUG)\\drivers

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)
	cmd /c if not exist $(OBJDIR_RELEASE)\\modbus_library md $(OBJDIR_RELEASE)\\modbus_library
	cmd /c if not exist $(OBJDIR_RELEASE)\\functions md $(OBJDIR_RELEASE)\\functions
	cmd /c if not exist $(OBJDIR_RELEASE)\\drivers md $(OBJDIR_RELEASE)\\drivers

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\unitTests.o: unitTests.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c unitTests.c -o $(OBJDIR_RELEASE)\\unitTests.o

$(OBJDIR_RELEASE)\\modbus_library\\mb.o: modbus_library\\mb.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c modbus_library\\mb.c -o $(OBJDIR_RELEASE)\\modbus_library\\mb.o

$(OBJDIR_RELEASE)\\modbus_library\\crc.o: modbus_library\\crc.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c modbus_library\\crc.c -o $(OBJDIR_RELEASE)\\modbus_library\\crc.o

$(OBJDIR_RELEASE)\\main.o: main.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.c -o $(OBJDIR_RELEASE)\\main.o

$(OBJDIR_RELEASE)\\functions\\f06.o: functions\\f06.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c functions\\f06.c -o $(OBJDIR_RELEASE)\\functions\\f06.o

$(OBJDIR_RELEASE)\\functions\\f03.o: functions\\f03.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c functions\\f03.c -o $(OBJDIR_RELEASE)\\functions\\f03.o

$(OBJDIR_RELEASE)\\drivers\\uartDriver.o: drivers\\uartDriver.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c drivers\\uartDriver.c -o $(OBJDIR_RELEASE)\\drivers\\uartDriver.o

$(OBJDIR_RELEASE)\\drivers\\timerDriver.o: drivers\\timerDriver.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c drivers\\timerDriver.c -o $(OBJDIR_RELEASE)\\drivers\\timerDriver.o

$(OBJDIR_RELEASE)\\drivers\\mcDriver.o: drivers\\mcDriver.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c drivers\\mcDriver.c -o $(OBJDIR_RELEASE)\\drivers\\mcDriver.o

$(OBJDIR_RELEASE)\\bsp.o: bsp.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c bsp.c -o $(OBJDIR_RELEASE)\\bsp.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)
	cmd /c rd $(OBJDIR_RELEASE)\\modbus_library
	cmd /c rd $(OBJDIR_RELEASE)\\functions
	cmd /c rd $(OBJDIR_RELEASE)\\drivers

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

